# 매일 자정에 휴일 데이터를 API에서 가져와 holidays.json 파일에 업데이트하도록 설정
name: Update Holidays

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  update-holidays:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch holiday data
        env:
          API_KEY: K9Q4h6VOX0IvCFcutwNBcoNQSlOb3uM3  # API Key 설정
        run: python fetch_holidays.py

      - name: Commit and Push holiday data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add holidays.json
          git commit -m "Update holidays data"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
