# 매일 자정에 휴일 데이터를 API에서 가져와 holidays.json 파일에 업데이트하도록 설정
name: Update Holidays

on:
   # schedule:
  #   - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:      # 수동 실행만 가능

jobs:
  update-holidays:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch holiday data
        env:
          API_KEY: ${{ secrets.API_KEY }}  # GitHub Secrets에 저장된 API Key 사용
        run: python fetch_holidays.py


      - name: Commit and Push holiday data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add holidays.json
          git commit -m "Update holidays data" || true
          git push origin main || true
